# Generated by Django 5.2.5 on 2025-08-26 11:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('internet', 'Internet'), ('utilities', 'Utilities (Electric/Water/Gas)'), ('supplies', 'Office Supplies'), ('salary', 'Salaries'), ('marketing', 'Marketing'), ('travel', 'Travel'), ('taxes', 'Taxes/Govt Fees'), ('maintenance', 'Maintenance/Repairs'), ('other', 'Other')], max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('mobile', 'Mobile Wallet')], default='bank', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='clients.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='projects.project')),
            ],
        ),
    ]
