# Generated by Django 5.2.5 on 2025-08-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='include_in_performance',
            field=models.BooleanField(default=True),
        ),
    ]
